apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: dev-ns
  labels:
    app: pod-afcsi
spec:
  containers:
  - name: cont1-ng
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: azurefile-vol1-csi
      mountPath: "/mnt/azure" 
  

  volumes:
  - name: azurefile-vol
    azureFile:
      secretName: azure-secret
      shareName: "azfileashu"
      readOnly: false
    


  - name: azurefile-vol1-csi
    csi:
      driver: file.csi.azure.com
      readOnly: false
      volumeAttributes:
        secretName: azure-secret
        shareName: "azfileashu"



# Note: The following azuredisk volume mount is deprecated and replaced by the CSI driver method// 
# volume mode "Ephemeral" not supported by driver disk.csi.azure.com (only supports ["Persistent"])

  # - name: azuredisk-vol1    ## Deprecated- this is the old way of mounting azuredisk volume. Now we are using CSI driver for azuredisk volume.
  #   azuredisk:
  #     secretName: azure-secret
  #     diskName: "azdiskashu"
  #     diskURI: "/subscriptions/0ae5ab6b-cbab-4b15-82a7-6ef0998daef7/resourceGroups/ashu-rgforaks/providers/Microsoft.Compute/disks/azdiskashu"
  #     cachingMode: ReadWrite
  #     fsType: ext4
  #     readOnly: false
  


  # - name: azuredisk-vol1-csi
  #   csi:
  #     driver: disk.csi.azure.com
  #     readOnly: false
  #     volumeAttributes:
  #       secretName: azure-secret
  #       diskName: "azdiskashu"
  #       diskURI: "https://ashujiostg.blob.core.windows.net/azdiskashu.vhd"
  #       cachingMode: ReadWrite
  #       fsType: ext4
        
  
  







    
    # env:
    # - name: AZURE_STORAGE_ACCOUNT_NAME
    #   value: "devopsstorageacc"
    # - name: AZURE_STORAGE_ACCOUNT_KEY
    #   value: "devopsstoragekey"
    # - name: AZURE_STORAGE_ACCOUNT_SHARE_NAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: azure-secret
    #       key: share-name
    # - name: AZURE_STORAGE_ACCOUNT_SHARE_MOUNT_PATH
    #   valueFrom:
    #     configMapKeyRef:
    #       name: azure-config
    #       key: share-mount-path
