apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-pvc
  namespace: nginx-ns1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: azure-file-pv
  storageClassName: ""
