apiVersion: v1
kind: Service
metadata:
  name: app2-ui-service
  namespace: flipkart-dev
  labels:
    app: app2-ui
    component: frontend
    environment: dev
spec:
  selector:
    app: app2-ui-pod-dev
  ports:
  - name: app2-ui-svctopod
    port: 8000
    targetPort: 80

  type: ClusterIP #enum: ClusterIP, ExternalName, LoadBalancer, NodePort
