apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-ui-pod-dev
  namespace: flipkart-dev
  labels:
    app: app2-ui
    component: frontend
    environment: dev

spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app2-ui-pod-dev

  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate # enum: Recreate, RollingUpdate

  template:
    metadata:

      labels:
        app: app2-ui-pod-dev

    spec:
      containers:
      - name: bkpod1
        image: traefik/whoami:v1.10.3
        ports:
        - containerPort: 80

  
