apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-c-env
  namespace: nginx-ns1
  labels:
    app: nginx
    env: production

spec:
  containers:
    - name: nginx-container
      image: nginx:latest

      env:
        - name: app1
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: APP_ENV

        - name: team1
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: TEAM