apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: nginx-ns1
  labels:
    app: nginx
spec:
  volumes:
    - name: nginx-volume1
      azureFile:
        readOnly: false
        secretName: azure-secret
        shareName: testfileshare
  containers:
    - name: nginx-container1
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-volume1
          mountPath: /usr/share/nginx/html


