apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-ns
  labels:
    app: nginx
spec:
  volumes:
    - name: nginx-volume
      emptyDir:
        sizeLimit: 500Mi
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html


