apiVersion: v1
kind: Service
metadata:
  name: nginx-ui-service
  namespace: dev-ns
  labels:
    svcfor: nginxui

  finalizers:
  - service.kubernetes.io/load-balancer-cleanup

spec:
  selector:
    app: nginx

  type: ClusterIP

  ports:
  - name: svctopod-nginx-ui-80
    port: 8001
    targetPort: 80
