apiVersion: v1
kind: Secret
metadata:
  name: azure-secret1
  namespace: dev-ns
type: Opaque
data:
  azurestorageaccountname: "YOUR_STORAGE_ACCOUNT_NAME"
  azurestorageaccountkey: "YOUR_STORAGE_ACCOUNT_KEY"