
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-azuredisk-csi-waitforfirstconsumer
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS

allowVolumeExpansion: true
reclaimPolicy: Delete # types of reclaimPolicy: Retain, Delete, Recycle
volumeBindingMode: Immediate # types of volumeBindingMode: Immediate, WaitForFirstConsumer