apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-ad
  namespace: nginx-af
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: azure-file
          mountPath: /usr/share/nginx/html
  volumes:
    - name: azure-file
      persistentVolumeClaim:
        claimName: azure-file-pvc